<img src="http://193.175.187.164/static/OEP_logo_2_no_text.svg" alt="OpenEnergy Platform" height="100" width="100"  align="left"/>
<img src="http://reiner-lemoine-institut.de//wp-content/uploads/2015/09/rlilogo.png" alt="RLI" height="100" width="100" align="right"/>

# OpenEnergy Platform

In [1]:
__copyright__ = "Reiner Lemoine Institut"
__license__   = "GNU Affero General Public License Version 3 (AGPL-3.0)"
__url__       = "https://github.com/openego/data_processing/blob/master/LICENSE"
__author__    = "Ludee"

In [2]:
from IPython.core.display import HTML

import requests
import pandas as pd

# oedb
oep_url= 'http://oep.iks.cs.ovgu.de/'

# token
your_token = ''

In [5]:
# select data
schema = 'boundaries'
table = 'bkg_vg250_2_lan'
where = 'reference_date=2016-01-01'
column = 'column=id&column=gen&column=geom'
orderby = 'gen'

result = requests.get(oep_url+'/api/v0/schema/'+schema+'/tables/'+table+'/rows/?where='+where+'&'+column, )
result.status_code

200

In [6]:
df = pd.DataFrame(result.json())
df

,gen,geom,id
0,Saarland,0106000000010000000103000000010000000209000091...,1
1,Baden-Württemberg,010600000005000000010300000002000000402A000028...,2
2,Nordrhein-Westfalen,010600000005000000010300000001000000D82300002F...,3
3,Bremen,01060000000400000001030000000100000062040000BE...,5
4,Hessen,010600000002000000010300000001000000181E000001...,6
5,Brandenburg,010600000004000000010300000002000000E02000002B...,7
6,Niedersachsen,010600000013000000010300000004000000DD36000087...,8
7,Mecklenburg-Vorpommern,010600000040000000010300000001000000473C000015...,9
8,Rheinland-Pfalz,010600000001000000010300000001000000481C00001A...,10
9,Berlin,01060000000100000001030000000100000065040000F1...,11
10,Baden-Württemberg (Bodensee),01060000000100000001030000000200000023050000AC...,12
11,Bremen,01060000000100000001030000000100000093000000C1...,13
12,Sachsen,010600000001000000010300000001000000A724000051...,21
13,Sachsen-Anhalt,0106000000020000000103000000040000000B1D00009B...,22
14,Hamburg,0106000000050000000103000000010000008D05000062...,23
15,Bayern (Bodensee),010600000001000000010300000001000000FF000000A4...,14
16,Baden-Württemberg,0106000000010000000103000000020000005C03000004...,15
17,Baden-Württemberg,01060000000400000001030000000100000028000000D0...,16
18,Thüringen,010600000001000000010300000002000000A51D000041...,31
19,Bayern,010600000001000000010300000001000000BC4A000009...,33
20,Niedersachsen,010600000001000000010300000001000000050000005B...,34
21,Hamburg,0106000000020000000103000000010000000E01000022...,17
22,Schleswig-Holstein,010600000015000000010300000001000000C5030000BA...,19
23,Niedersachsen,0106000000100000000103000000010000003600000018...,25
24,Schleswig-Holstein,01060000001D000000010300000001000000EE31000050...,26
25,Schleswig-Holstein,01060000002500000001030000000200000034090000DE...,27
26,Mecklenburg-Vorpommern,01060000000300000001030000000100000006000000A4...,29
27,Mecklenburg-Vorpommern,010600000020000000010300000002000000C104000010...,30